#!/bin/bash

CATEGORY=$1
NAME=$2

mkdir -p $CATEGORY/$NAME

CFG=$CATEGORY/$NAME/$NAME.cfg
DWT=$CATEGORY/$NAME/$NAME.dwt
OUT=$CATEGORY/$NAME/$NAME.out
ERR=$CATEGORY/$NAME/$NAME.err

touch $CFG
touch $DWT

echo "---" >> $CFG
echo "description: \"short description goes here\"" >> $CFG
echo "name: $NAME" >> $CFG
echo "loops: 1" >> $CFG
echo "skip: no" >> $CFG

