on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and test Dwt
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      run: |
        make -j2
