name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and test Dwt
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      run: |
        make -j2
    - name: Test
      run: |
        sudo pip install tqdm colorama
        export PATH=$PWD/bin:$PATH
        dwt
        test/fuzzgen.sh
        test/runner.py --jenkins
        test/postprocess.sh
