name: performance profile

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    name: Build and test Dwt
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      run: |
        make profile=performance -j2
    - name: Test
      run: |
        export PATH=$PWD/bin:$PATH
        dwt
        test/fuzzgen.sh > /dev/null
        cd test
        ./tester
